=== furycd001/dots/fedorakde2/kdebase/kate/data/language.dtd
<!ELEMENT language (highlighting, general?)>
<!ATTLIST language
  name CDATA #REQUIRED
  section (Sources|Markup|Other|Scripts) #REQUIRED
  extensions CDATA #REQUIRED
  mimetype CDATA #REQUIRED
  casesensitive (0|1) #IMPLIED
>

<!ELEMENT general (comments?, keywords?)>
<!ATTLIST general
>

<!ELEMENT comments (comment)+>
<!ATTLIST comments
>

<!ELEMENT comment EMPTY>
<!ATTLIST comment
  name (singleLine|multiLine) #REQUIRED
  start CDATA #REQUIRED
  end CDATA #IMPLIED
>

<!ELEMENT keywords EMPTY>
<!ATTLIST keywords
  casesensitive CDATA #IMPLIED
  weakDeliminator CDATA #IMPLIED
>

<!ELEMENT highlighting (list*, contexts, itemDatas)>
<!ATTLIST highlighting
>

<!ELEMENT list (item)+>
<!ATTLIST list
  name (types|keywords|attribute-definitions|literals|definitions) #REQUIRED
>

<!ELEMENT item (#PCDATA)>

<!ELEMENT contexts (context)+>

<!ELEMENT context (keyword | Float | HlCOct | HlCHex | Int | DetectChar | Detect2Chars | AnyChar | StringDetect | RegExpr | LineContinue | HlCStringChar | RangeDetect | HlCChar)*>
<!ATTLIST context
  attribute CDATA #REQUIRED
  lineEndContext NMTOKEN #REQUIRED
  lineBeginContext NMTOKEN #IMPLIED
  name CDATA #IMPLIED
>

<!ELEMENT keyword EMPTY>
<!ATTLIST keyword
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String (types|keywords|attribute-definitions|literals|definitions) #REQUIRED
  weakDelimiter CDATA #IMPLIED
>

<!ELEMENT Float (AnyChar)*>
<!ATTLIST Float
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCOct EMPTY>
<!ATTLIST HlCOct
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCHex EMPTY>
<!ATTLIST HlCHex
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCChar EMPTY>
<!ATTLIST HlCChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT Int (StringDetect)*>
<!ATTLIST Int
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT DetectChar EMPTY>
<!ATTLIST DetectChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  char CDATA #REQUIRED
>

<!ELEMENT Detect2Chars EMPTY>
<!ATTLIST Detect2Chars
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  char CDATA #REQUIRED
  char1 CDATA #REQUIRED
>

<!ELEMENT AnyChar EMPTY>
<!ATTLIST AnyChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String CDATA #REQUIRED
>

<!ELEMENT StringDetect EMPTY>
<!ATTLIST StringDetect
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String CDATA #REQUIRED
  insensitive (TRUE|FALSE) #REQUIRED
>

<!ELEMENT RegExpr EMPTY>
<!ATTLIST RegExpr
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String CDATA #REQUIRED
>

<!ELEMENT LineContinue EMPTY>
<!ATTLIST LineContinue
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCStringChar EMPTY>
<!ATTLIST HlCStringChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT RangeDetect EMPTY>
<!ATTLIST RangeDetect
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  char CDATA #REQUIRED
  char1 CDATA #REQUIRED
>

<!ELEMENT itemDatas (itemData)+>
<!ATTLIST itemDatas
>

<!ELEMENT itemData EMPTY>
<!ATTLIST itemData
  name CDATA #REQUIRED
  defStyleNum CDATA #REQUIRED
  color CDATA #IMPLIED
  selColor CDATA #IMPLIED
  italic CDATA #IMPLIED
  bold CDATA #IMPLIED
>

=== furycd001/dots/fedorakde2/kdebase/kate/data/perl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Perl" section="Scripts" extensions="*.pl;*.pm" mimetype="">
<highlighting>
	<list name="keywords">
		<item> sub </item>
		<item> bless </item>
		<item> caller </item>
		<item> cmp </item>
		<item> print </item>
		<item> echo </item>
		<item> die </item>
		<item> import </item>
		<item> lt </item>
		<item> le </item>
		<item> local </item>
		<item> last </item>
		<item> ! </item>
		<item> || </item>
		<item> eq </item>
		<item> ne </item>
		<item> use </item>
		<item> elsif </item>
		<item> my </item>
		<item> foreach </item>
		<item> wantarray </item>
		<item> push </item>
		<item> pop </item>
		<item> dbmclose </item>
		<item> dbmopen </item>
		<item> dump </item>
		<item> each </item>
		<item> ge </item>
		<item> gt </item>
		<item> split </item>
		<item> open </item>
		<item> close </item>
		<item> eval </item>
		<item> chomp </item>
		<item> chop </item>
		<item> unless </item>
		<item> undef </item>
		<item> next </item>
		<item> unlink </item>
		<item> new </item>
		<item> and </item>
		<item> not </item>
		<item> no </item>
		<item> ref </item>
		<item> redo </item>
		<item> require </item>
		<item> tied </item>
		<item> tie </item>
		<item> untie </item>
		<item> or </item>
		<item> xor </item>
		<item> continue </item>
		<item> do </item>
		<item> else </item>
		<item> for </item>
		<item> goto </item>
		<item> if </item>
		<item> return </item>
		<item> switch </item>
		<item> while </item>
	</list>

	<contexts>

		<context attribute="0" lineEndContext="0" name="Normal">
			<keyword attribute="1" context="0" String="keywords"/>
			<keyword attribute="2" context="0" String="types"/>
			<HlCOct attribute="4" context="0"/>
			<HlCHex attribute="5" context="0"/>
			<Int attribute="3" context="0" />
			<HlCChar attribute="7" context="0"/>
			<RegExpr attribute="1" context="0" String="^#!.*" />
			<DetectChar attribute="8" context="1" char="&quot;"/>
			<DetectChar attribute="8" context="12" char="'"/>
			<DetectChar attribute="9" context="1" char="`"/>
			<Detect2Chars attribute="10" context="2" char="/" char1="/"/>
			<Detect2Chars attribute="10" context="3" char="/" char1="*"/>
			<Detect2Chars attribute="12" context="9" char="s" char1="/" />
			<DetectChar attribute="12" context="8" char="/" />
			<AnyChar attribute="11" context="0" String="!%&amp;()+,-&lt;=&gt;?[]^{|}~"/>
			<RegExpr attribute="3" context="0" String="\$[0-9]+" />
			<RegExpr attribute="2" context="0" String="\$\#?[a-zA-Z_]+[a-zA-Z0-9_]*" />
			<RegExpr attribute="12" context="0" String="\s+\:" />
			<DetectChar attribute="10" context="2" char="#" />
		</context>

		<context attribute="8" lineEndContext="1" name="String">
			<LineContinue attribute="8" context="6"/>
			<HlCStringChar attribute="9" context="1"/>
			<DetectChar attribute="8" context="0" char="&quot;"/>
			<RegExpr attribute="3" context="1" String="\$[0-9]+" />
			<RegExpr attribute="2" context="1" String="\$[a-zA-Z_]*[a-zA-Z0-9_]*" />
		</context>

		<context attribute="10" lineEndContext="0" name="Commentar 1"/>

		<context attribute="10" lineEndContext="3" name="Commentar 2">
			<Detect2Chars attribute="10" context="0" char="*" char1="/"/>
		</context>

		<context attribute="12" lineEndContext="0" name="Preprocessor">
			<LineContinue attribute="12" context="7"/>
			<RangeDetect attribute="13" context="4" char="&quot;" char1="&quot;"/>
			<RangeDetect attribute="13" context="4" char="&lt;" char1="&gt;"/>
			<Detect2Chars attribute="10" context="2" char="/" char1="/"/>
			<Detect2Chars attribute="10" context="5" char="/" char1="*"/>
		</context>

		<context attribute="10" lineEndContext="5" name="Commentar/Preprocessor">
			<Detect2Chars attribute="10" context="4" char="*" char1="/" />
		</context>

		<context attribute="0" lineEndContext="1" name="Some Context"/>

		<context attribute="0" lineEndContext="4" name="Some Context2"/>

		<context attribute="12" lineEndContext="8" >
			<RegExpr attribute="9" context="8" String="\\[\/\[\]dDwWsSnrtfb0\$@]?" />
			<RegExpr attribute="9" context="8" String="\^[\/\[\]]?" />
			<DetectChar attribute="12" context="0" char="/" />
		</context>

		<context attribute="12" lineEndContext="9">
			<RegExpr attribute="9" context="9" String="\\[\/\[\]dDwWsSnrtfb0\$@]?" />
			<RegExpr attribute="9" context="9" String="\^[\/\[\]]?" />
			<RegExpr attribute="12" context="10" String="\/" />
		</context>

		<context attribute="12" lineEndContext="10">
			<RegExpr attribute="9" context="10" String="\\[\/\[\]dDwWsSnrtfb0\$@]?" />
			<RegExpr attribute="9" context="10" String="\^[\/\[\]]?" />
			<RegExpr attribute="12" context="0" String="\/g?" />
		</context>

		<context attribute="9" lineEndContext="11">
			<DetectChar attribute="9" context="0" char="`"/>
		</context>

		<context attribute="8" lineEndContext="1" name="String2">
			<LineContinue attribute="8" context="6"/>
			<Detect2Chars attribute="9" context="12" char="\" char1="'"/>
			<DetectChar attribute="8" context="0" char="'"/>
		</context>
	</contexts>

	<itemDatas>
		<itemData name="Normal Text" defStyleNum="dsNormal"/>
		<itemData name="Keyword"  defStyleNum="dsKeyword"/>
		<itemData name="Data Type"  defStyleNum="dsDataType"/>
		<itemData name="Decimal"  defStyleNum="dsDecVal"/>
		<itemData name="Octal"  defStyleNum="dsBaseN"/>
		<itemData name="Hex"  defStyleNum="dsBaseN"/>
		<itemData name="Float"  defStyleNum="dsFloat"/>
		<itemData name="Char"  defStyleNum="dsChar"/>
		<itemData name="String"  defStyleNum="dsString"/>
		<itemData name="String Char"  defStyleNum="dsChar"/>
		<itemData name="Comment"  defStyleNum="dsComment"/>
		<itemData name="Symbol"  defStyleNum="dsNormal"/>
		<itemData name="Pattern"  defStyleNum="dsOthers"/>
	</itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="#" />
    </comments>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/rpmspec.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="RPM Spec" section="Other" extensions="*.spec" mimetype="">
  <highlighting>
    <list name="keywords">
        <item> Name </item>
                <item> Summary </item>
                <item> Version </item>
                <item> Release </item>
                <item> Source </item>
                <item> Group </item>
                <item> BuildRoot </item>
                <item> Copyright </item>
                <item> Packager </item>
                <item> Url </item>
                <item> URL </item>
                <item> Prefix </item>
                <item> Requires </item>
                <item> BuildRequires </item>
                <item> Serial </item>
                <item> Vendor </item>
                <item> License </item>
    </list>
    <list name="types">
      <item> GPL </item>
      <item> LGPL </item>
      <item> Artistic </item>
    </list>
    <contexts>

      <context attribute="0" lineEndContext="0">
         <keyword attribute="1" context="0" String="keywords"/>
         <keyword attribute="5" context="0" String="types"/>
         <RegExpr attribute="2" context="0" String="%[a-zA-Z0-9_]*" />
         <DetectChar attribute="3" context="1" char="#" />
         <RegExpr attribute="1" context="2" String="\{[a-zA-Z0-9_]*" />
         <RegExpr attribute="4" context="3" String="&lt;\s*[a-zA-Z0-9_@\.]*" />
         <RegExpr attribute="5" context="0" String="\$[a-zA-Z0-9_]*" />
         <RegExpr attribute="1" context="0" String="(Source|Patch)[0-9]*" />
         <RegExpr attribute="1" context="0" String="^\*.*" />    <!-- ChangeLog -->
         <Int attribute="4" context="0" />
   </context>

       <context attribute="3" lineEndContext="0"/>

       <context attribute="1" lineEndContext="0">
          <DetectChar attribute="1" char="}" context="0"/>
       </context>

       <context attribute="4" lineEndContext="0">
           <DetectChar attribute="4" char="&gt;" context="0"/>
       </context>

    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword"  defStyleNum="dsKeyword"/>
      <itemData name="Red"  defStyleNum="dsString"/>
      <itemData name="Comment"  defStyleNum="dsComment"/>
      <itemData name="Blue"  defStyleNum="dsDecVal"/>
      <itemData name="Data" defStyleNum="dsDataType"/>
    </itemDatas>
  </highlighting>
   <general>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/ruby.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Ruby" section="Sources" extensions="*.rb" mimetype="text/x-ruby">
  <highlighting>

    <list name = "keywords">
	<item> __FILE__ </item>
	<item> __LINE__ </item>
	<item> BEGIN </item>
	<item> END </item>
	<item> and </item>
	<item> begin </item>
	<item> break </item>
	<item> and </item>
	<item> begin </item>
	<item> break </item>
	<item> case </item>
	<item> catch </item>
	<item> defined? </item>
	<item> do </item>
	<item> else </item>
	<item> elsif </item>
	<item> end </item>
	<item> ensure </item>
	<item> for </item>
	<item> if </item>
	<item> in </item>
	<item> include </item>
	<item> next </item>
	<item> not </item>
	<item> or </item>
	<item> private </item>
	<item> protected </item>
	<item> public </item>
	<item> redo </item>
	<item> require </item>
	<item> rescue </item>
	<item> retry </item>
	<item> return </item>
	<item> super </item>
	<item> then </item>
	<item> throw </item>
	<item> unless </item>
	<item> until </item>
	<item> when </item>
	<item> while </item>
	<item> yield </item>
    </list>

    <list name = "attribute-definitions">
	<item> attr </item>
	<item> attr_reader </item>
	<item> attr_writer </item>
	<item> attr_accessor </item>
    </list>

    <list name = "definitions">
	<item> alias </item>
	<item> module </item>
	<item> class </item>
	<item> def </item>
	<item> undef </item>
    </list>

    <list name = "literals">
	<item> nil </item>
	<item> false </item>
	<item> true </item>
    </list>

    <contexts>
 <context name = "Normal" attribute = "Normal Text" lineEndContext="0">
	<keyword String = "keywords" attribute = "Keyword" context="0"/>
	<keyword String = "literals" attribute = "Literal" context="0"/>
	<StringDetect String= "self" attribute = "Instance Variable" context="0" insensitive="FALSE"/>
	<keyword String = "attribute-definitions" attribute = "Attribute Definition" context="0"/>
	<!-- group>
		<keyword String = "definitions" attribute = "Keyword" context="0"/>
		<whitespace/>
		<regexp match = "[a-zA-Z_0-9.]+" attribute = "Definition"/>
 	</group -->
	<Float attribute = "Float" context="0"/>
	<Int attribute = "Decimal" context="0"/>
	<HlCChar attribute = "Char" context="0"/>
	<DetectChar char = "." attribute = "Operator" context="0"/>
	<StringDetect  String = "&amp;&amp;" attribute = "Operator" context="0" insensitive="FALSE"/>
	<RegExpr String = ":[^\s]+" attribute = "Symbol" context="0"/>
	<RegExpr String = "/[^\s]+/" attribute = "Delimiter" context="0"/>
	<StringDetect String = "||" attribute = "Operator" context="0"  insensitive="FALSE"/>
	<RegExpr String = "\s\?\s" attribute = "Operator" context="0"/>
	<RegExpr String = "\s:\s"  attribute = "Operator" context="0"/>
	<RegExpr String = "[&lt;&gt;!^&#61;&#37;+*~/-]+" attribute = "Operator" context="0"/>
	<DetectChar char = '"' attribute = "String" context = "2"/>
	<DetectChar char= "'" attribute = "String" context="3"/>
	<RegExpr String = "^##$" attribute = "Main Comment" context="1"/>
	<RegExpr String = "^#$" attribute = "Comment" context="0"/>
	<RegExpr String = "[\[\]\{\}|]+" attribute = "Delimiter" context="0"/>
	<RegExpr String = "[A-Z_]+" attribute = "Global Constant" context="0"/>
	<RegExpr String = "$[a-zA-Z_0-9]+" attribute = "Global Variable" context="0"/>
	<RegExpr String = "@[a-zA-Z_0-9]+" attribute = "Instance Variable" context="0"/>
	<RegExpr String = "@@[a-zA-Z_0-9]+" attribute = "Class Variable" context="0"/>
      </context>

      <context name = "Main Comment" attribute = "Main Comment" lineEndContext="0">
	<RegExpr String = "^##$" attribute = "Main Comment" context = "0"/>
	<RegExpr String = "^#$" attribute = "Main Comment" context = "0"/>
      </context>

      <context name = "Quoted String" attribute = "String" lineEndContext="0">
	<RegExpr String = "#{[^}]+}" attribute = "Expression" context = "0"/>
	<HlCChar attribute = "Char" context = "0"/>
	<DetectChar char = '"' attribute = "String" context = "0"/>
      </context>

      <context name = "Apostrophed String" attribute = "String" lineEndContext="0">
	<RegExpr String = "#{[^}]+}" attribute = "Expression" context = "0"/>
	<HlCChar attribute = "Char" context = "0"/>
	<DetectChar char = "'" attribute = "String" context = "0"/>
      </context>


    </contexts>

    <itemDatas>
      <itemData name = "Normal Text" defStyleNum ="dsNormal"/>
      <itemData name = "Keyword" defStyleNum ="dsKeyword"/>
      <itemData name = "Definition" defStyleNum ="dsNormal"/>
      <itemData name = "Literal" defStyleNum ="dsDecVal"/>
      <itemData name = "Decimal" defStyleNum ="dsDecVal"/>
      <itemData name = "Float" defStyleNum ="dsFloat"/>
      <itemData name = "Char" defStyleNum ="dsChar"/>
      <itemData name = "Symbol" defStyleNum ="dsString"/>
      <itemData name = "String" defStyleNum ="dsString"/>
      <itemData name = "Main Comment" defStyleNum ="dsComment" />
      <itemData name = "Comment" defStyleNum ="dsComment"/>
      <itemData name = "Delimiter" defStyleNum ="dsChar"/> 
      <itemData name = "Global Constant" defStyleNum ="dsDecVal"/>
      <itemData name = "Global Variable" defStyleNum ="dsOthers"/>
      <itemData name = "Instance Variable" defStyleNum ="dsOthers"/>
      <itemData name = "Class Variable" defStyleNum ="dsOthers"/>
      <itemData name = "Expression" defStyleNum ="dsOthers"/>
      <itemData name = "Operator" defStyleNum ="dsChar"/> 
      <itemData name = "Attribute Definition" defStyleNum ="dsOthers"/>
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="#" />
    </comments>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/c.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="C" section="Sources" extensions="*.c;*.C;*.h" mimetype="text/x-c++-src;text/x-chdr;text/x-csrc">
  <highlighting>
    <list name="keywords">
      <item> break </item>
      <item> case </item>
      <item> continue </item>
      <item> default </item>
      <item> do </item>
      <item> else </item>
      <item> enum </item>
      <item> extern </item>
      <item> for </item>
      <item> goto </item>
      <item> if </item>
      <item> return </item>
      <item> sizeof </item>
      <item> struct </item>
      <item> switch </item>
      <item> typedef </item>
      <item> union </item>
      <item> while </item>
    </list>
    <list name="types">
      <item> auto </item>
      <item> char </item>
      <item> const </item>
      <item> double </item>
      <item> float </item>
      <item> int </item>
      <item> long </item>
      <item> register </item>
      <item> short </item>
      <item> signed </item>
      <item> static </item>
      <item> unsigned </item>
      <item> void </item>
      <item> volatile </item>
    </list>
    <contexts>
      <context attribute="0" lineEndContext="0">
        <keyword attribute="1" context="0" String="keywords"/>
        <keyword attribute="2" context="0" String="types"/>
        <Float attribute="6" context="0">
          <AnyChar String="fF" attribute="6" context="0"/>
        </Float>
        <HlCOct attribute="4" context="0"/>
        <HlCHex attribute="5" context="0"/>
        <Int attribute="3" context="0" >
          <StringDetect attribute="3" context="0" String="ULL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LUL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LLU" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="UL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LU" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="U" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="L" insensitive="TRUE"/>
        </Int>
        <HlCChar attribute="7" context="0"/>
        <DetectChar attribute="8" context="1" char="&quot;"/>
        <Detect2Chars attribute="10" context="2" char="/" char1="/"/>
        <Detect2Chars attribute="10" context="3" char="/" char1="*"/>
        <AnyChar attribute="11" context="0" String="!%&amp;()+,-&lt;=&gt;?[]^{|}~"/>
        <StringDetect attribute="10" context="8" String="#if 0" insensitive="FALSE"/>
        <RegExpr attribute="12" context="4" String="^#"/>
      </context>
      <context attribute="8" lineEndContext="0">
        <LineContinue attribute="8" context="6"/>
        <HlCStringChar attribute="9" context="1"/>
        <DetectChar attribute="8" context="0" char="&quot;"/>
      </context>
      <context attribute="10" lineEndContext="0">
        <RegExpr attribute="3" context="2" String="(FIXME|TODO)" />
      </context>
      <context attribute="10" lineEndContext="3">
        <Detect2Chars attribute="10" context="0" char="*" char1="/"/>
        <RegExpr attribute="3" context="3" String="(FIXME|TODO)" />
      </context>
      <context attribute="12" lineEndContext="0">
        <LineContinue attribute="12" context="7"/>
        <RangeDetect attribute="13" context="4" char="&quot;" char1="&quot;"/>
        <RangeDetect attribute="13" context="4" char="&lt;" char1="&gt;"/>
        <Detect2Chars attribute="10" context="2" char="/" char1="/"/>
        <Detect2Chars attribute="10" context="5" char="/" char1="*"/>
      </context>
      <context attribute="10" lineEndContext="5">
        <Detect2Chars attribute="10" context="4" char="*" char1="/" />
      </context>
      <context attribute="0" lineEndContext="1" />
      <context attribute="0" lineEndContext="4" />
      <context attribute="10" lineEndContext="8">
          <RegExpr attribute="3" context="8" String="(FIXME|TODO)" /> 
          <RegExpr attribute="10" context="0" String="^#endif" />
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword"  defStyleNum="dsKeyword"/>
      <itemData name="Data Type"  defStyleNum="dsDataType"/>
      <itemData name="Decimal"  defStyleNum="dsDecVal"/>
      <itemData name="Octal"  defStyleNum="dsBaseN"/>
      <itemData name="Hex"  defStyleNum="dsBaseN"/>
      <itemData name="Float"  defStyleNum="dsFloat"/>
      <itemData name="Char"  defStyleNum="dsChar"/>
      <itemData name="String"  defStyleNum="dsString"/>
      <itemData name="String Char"  defStyleNum="dsChar"/>
      <itemData name="Comment"  defStyleNum="dsComment"/>
      <itemData name="Symbol"  defStyleNum="dsNormal"/>
      <itemData name="Preprocessor"  defStyleNum="dsOthers"/>
      <itemData name="Prep. Lib"  defStyleNum="dsOthers"/> <!--,Qt::darkYellow,Qt::yellow,false,false)); -->
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="multiLine" start="/*" end="*/" />
    </comments>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/ada.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Ada" section="Sources" extensions="*.a" mimetype="text/x-ada-src">
        <highlighting>
                <list name="keywords">
                        <item> abort </item>
                        <item> abs </item>
                        <item> accept </item>
                        <item> access </item>
                        <item> all </item>
                        <item> and </item>
                        <item> array </item>
                        <item> at </item>
                        <item> begin </item>
                        <item> body </item>
                        <item> case </item>
                        <item> constant </item>
                        <item> declare </item>
                        <item> delay </item>
                        <item> delta </item>
                        <item> digits </item>
                        <item> do </item>
                        <item> else </item>
                        <item> elsif </item>
                        <item> end </item>
                        <item> entry </item>
                        <item> exception </item>
                        <item> exit </item>
                        <item> for </item>
                        <item> function </item>
                        <item> generic </item>
                        <item> goto </item>
                        <item> if </item>
                        <item> in </item>
                        <item> is </item>
                        <item> limited </item>
                        <item> loop </item>
                        <item> mod </item>
                        <item> new </item>
                        <item> not </item>
                        <item> null </item>
                        <item> of </item>
                        <item> or </item>
                        <item> others </item>
                        <item> out </item>
                        <item> package </item>
                        <item> pragma </item>
                        <item> private </item>
                        <item> procedure </item>
                        <item> raise </item>
                        <item> range </item>
                        <item> rem </item>
                        <item> record </item>
                        <item> renames </item>
                        <item> return </item>
                        <item> reverse </item>
                        <item> select </item>
                        <item> separate </item>
                        <item> subtype </item>
                        <item> task </item>
                        <item> terminate </item>
                        <item> then </item>
                        <item> type </item>
                        <item> use </item>
                        <item> when </item>
                        <item> while </item>
                        <item> with </item>
                        <item> xor </item>
                </list>
                <contexts>
                        <context attribute="0" lineEndContext="0">
                                <keyword attribute="1" context="0" String="keywords"/>
                                <!-- HlAdaBaseN attribute="3" context="0"/ -->
                                <Float attribute="4" context="0"/>
                                <Int attribute="2" context="0"/>
                                <RegExpr attribute="5" context="0" String="'.'"/> <!-- Ada Char -->
                                <DetectChar attribute="6" context="1" char="&quot;"/>
                                <Detect2Chars attribute="7" context="2" char="-" char1="-"/>
                        </context>
                        <context attribute="6" lineEndContext="0">
                                <DetectChar attribute="6" context="0" char="&quot;"/>
                        </context>
                        <context attribute="7" lineEndContext="0"/>
                </contexts>
                <itemDatas>
                        <itemData name="Normal Text" defStyleNum="dsNormal" />
                        <itemData name="Keyword"     defStyleNum="dsKeyword" />
                        <itemData name="Decimal"     defStyleNum="dsDecVal" />
                        <itemData name="Base-N"      defStyleNum="dsBaseN" />
                        <itemData name="Float"       defStyleNum="dsFloat" />
                        <itemData name="Char"        defStyleNum="dsChar" />
                        <itemData name="String"      defStyleNum="dsString" />
                        <itemData name="Comment"     defStyleNum="dsComment" />
                </itemDatas>
  </highlighting>
  <general>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/diff.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Diff" section="Other" extensions="*.diff;*patch" mimetype="text/plain; text/x-c++-src;text/x-c++-hdr;text/x-c-hdr;text/x-c++-src">
  <highlighting>

    <contexts>
      <context attribute="0" lineEndContext="0">
      	<RegExpr attribute="1" context="1" String="^(\+\+\+|\-\-\-|\*\*\*|diff|\d)" />
	<RegExpr attribute="4" context="2" String="^(\+|&gt;|!)" />
	<RegExpr attribute="3" context="3" String="^(\-|&lt;)" />
	<RegExpr attribute="2" context="4" String="^\@\@" />
      </context>

      <context attribute="1" lineEndContext="0" />
      <context attribute="4" lineEndContext="0" />
      <context attribute="3" lineEndContext="0" />
      <context attribute="2" lineEndContext="0" />

    </contexts>

    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword"  defStyleNum="dsKeyword"/>
      <itemData name="Data Type"  defStyleNum="dsDataType"/>
      <itemData name="Removed line"  defStyleNum="dsOthers"/>
      <itemData name="Added line"  defStyleNum="dsString"/>
      <itemData name="Comment"  defStyleNum="dsComment"/>
    </itemDatas>
  </highlighting>
  <general>
    <keywords casesensitive="1" />
  </general>
</language>
