=== furycd001/dots/fedorakde2/kdebase/kate/data/language.dtd
<!ELEMENT language (highlighting, general?)>
<!ATTLIST language
  name CDATA #REQUIRED
  section (Sources|Markup|Other|Scripts) #REQUIRED
  extensions CDATA #REQUIRED
  mimetype CDATA #REQUIRED
  casesensitive (0|1) #IMPLIED
>

<!ELEMENT general (comments?, keywords?)>
<!ATTLIST general
>

<!ELEMENT comments (comment)+>
<!ATTLIST comments
>

<!ELEMENT comment EMPTY>
<!ATTLIST comment
  name (singleLine|multiLine) #REQUIRED
  start CDATA #REQUIRED
  end CDATA #IMPLIED
>

<!ELEMENT keywords EMPTY>
<!ATTLIST keywords
  casesensitive CDATA #IMPLIED
  weakDeliminator CDATA #IMPLIED
>

<!ELEMENT highlighting (list*, contexts, itemDatas)>
<!ATTLIST highlighting
>

<!ELEMENT list (item)+>
<!ATTLIST list
  name (types|keywords|attribute-definitions|literals|definitions) #REQUIRED
>

<!ELEMENT item (#PCDATA)>

<!ELEMENT contexts (context)+>

<!ELEMENT context (keyword | Float | HlCOct | HlCHex | Int | DetectChar | Detect2Chars | AnyChar | StringDetect | RegExpr | LineContinue | HlCStringChar | RangeDetect | HlCChar)*>
<!ATTLIST context
  attribute CDATA #REQUIRED
  lineEndContext NMTOKEN #REQUIRED
  lineBeginContext NMTOKEN #IMPLIED
  name CDATA #IMPLIED
>

<!ELEMENT keyword EMPTY>
<!ATTLIST keyword
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String (types|keywords|attribute-definitions|literals|definitions) #REQUIRED
  weakDelimiter CDATA #IMPLIED
>

<!ELEMENT Float (AnyChar)*>
<!ATTLIST Float
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCOct EMPTY>
<!ATTLIST HlCOct
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCHex EMPTY>
<!ATTLIST HlCHex
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCChar EMPTY>
<!ATTLIST HlCChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT Int (StringDetect)*>
<!ATTLIST Int
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT DetectChar EMPTY>
<!ATTLIST DetectChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  char CDATA #REQUIRED
>

<!ELEMENT Detect2Chars EMPTY>
<!ATTLIST Detect2Chars
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  char CDATA #REQUIRED
  char1 CDATA #REQUIRED
>

<!ELEMENT AnyChar EMPTY>
<!ATTLIST AnyChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String CDATA #REQUIRED
>

<!ELEMENT StringDetect EMPTY>
<!ATTLIST StringDetect
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String CDATA #REQUIRED
  insensitive (TRUE|FALSE) #REQUIRED
>

<!ELEMENT RegExpr EMPTY>
<!ATTLIST RegExpr
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  String CDATA #REQUIRED
>

<!ELEMENT LineContinue EMPTY>
<!ATTLIST LineContinue
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT HlCStringChar EMPTY>
<!ATTLIST HlCStringChar
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
>

<!ELEMENT RangeDetect EMPTY>
<!ATTLIST RangeDetect
  attribute CDATA #REQUIRED
  context NMTOKEN #REQUIRED
  char CDATA #REQUIRED
  char1 CDATA #REQUIRED
>

<!ELEMENT itemDatas (itemData)+>
<!ATTLIST itemDatas
>

<!ELEMENT itemData EMPTY>
<!ATTLIST itemData
  name CDATA #REQUIRED
  defStyleNum CDATA #REQUIRED
  color CDATA #IMPLIED
  selColor CDATA #IMPLIED
  italic CDATA #IMPLIED
  bold CDATA #IMPLIED
>

=== furycd001/dots/fedorakde2/kdebase/kate/data/html.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="HTML" section="Markup" extensions="*.html;*.htm;*.shtml;*.shtm" mimetype="text/html">
  <highlighting>
    <contexts>
       <context attribute="0" lineEndContext="0">
         <RegExpr attribute="1" context="1" String="&lt;\s*\/?\s*[a-zA-Z0-9_]*" />
       </context>

       <context attribute="2" lineEndContext="1">
         <DetectChar attribute="1" context="0" char="&gt;"/>
         <RegExpr attribute="0" context="2" String="\s*=\s*"/>
       </context>

       <context attribute="8" lineEndContext="2">
         <RegExpr attribute="3" context="1" String="\s*#?[a-zA-Z0-9]*" />
         <DetectChar attribute="3" context="3" char="&quot;" />
       </context>

       <context attribute="3" lineEndContext="3">
         <DetectChar attribute="3" context="1" char="&quot;" />
       </context>

       <context attribute="5" lineEndContext="0"/>
       <context attribute="4" lineEndContext="0">
         <DetectChar attribute="4" context="0" char="'"/>
       </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword" defStyleNum="dsKeyword"/>
      <itemData name="Identifier" defStyleNum="dsOthers"/>
      <itemData name="Types" defStyleNum="dsDataType"/>
      <itemData name="String" defStyleNum="dsString"/>
      <itemData name="Comment" defStyleNum="dsComment"/>
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="multiLine" start="&lt;!--" end="//--&gt;" />
    </comments>
    <keywords casesensitive="0" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/bash.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Bash" section="Scripts" extensions="" mimetype="text/x-shellscript">
        <highlighting>
                 <list name = "keywords">
                        <item> break </item>
                        <item> case </item>
                        <item> done </item>
                        <item> do </item>
                        <item> elif </item>
                        <item> else </item>
                        <item> esac </item>
                        <item> exit </item>
                        <item> export </item>
                        <item> fi </item>
                        <item> for </item>
                        <item> function </item>
                        <item> if </item>
                        <item> in </item>
                        <item> return </item>
                        <item> select </item>
                        <item> then </item>
                        <item> until </item>
                        <item> while </item>
                        <item> . </item>
                </list>


        <contexts>
                <context name = "Base" attribute = "0" lineEndContext="0">
                        <keyword String = "keywords" attribute = "1" context="0"/>
                        <Int attribute = "2" context="0"/>
                        <RegExpr String = "$[0-9]+" attribute = "8" context="0"/>
                        <AnyChar String = "|&lt;&gt;=;" attribute = "9" context="0"/>
                        <DetectChar char = '"' attribute = "5" context="0"/>
                        <DetectChar char="`" attribute = "7" context = "2"/>
                        <RegExpr String= "^#.*$" attribute = "6" context="0"/>
                </context>

                <context name = "String" attribute = "5" lineEndContext="1">
                        <HlCChar attribute = "4" context = "1"/>
                        <DetectChar char = '"' attribute = "5" context = "0"/>
                </context>

                <context name = "Substitution" attribute = "7" lineEndContext="2">
                        <DetectChar char = "`" attribute = "7" context = "0"/>
                </context>
        </contexts>

        <itemDatas>
                <itemData name = "Normal Text" defStyleNum = "dsNormal"/>
                <itemData name = "Keyword" defStyleNum = "dsKeyword"/>
                <itemData name = "Decimal" defStyleNum = "dsDecVal"/>
                <itemData name = "Float" defStyleNum = "dsFloat"/>
                <itemData name = "Char" defStyleNum = "dsChar"/>
                <itemData name = "String" defStyleNum = "dsString"/>
                <itemData name = "Comment" defStyleNum = "dsComment"/>
                <itemData name = "Substitution" defStyleNum = "dsOthers"/>
                <itemData name = "Parameter" defStyleNum = "dsOthers"/>
                <itemData name = "Operator" defStyleNum = "dsOthers"/>
        </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="#" />
    </comments>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/cpp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="C++" section="Sources" extensions="*.cxx;*.cpp;*.cc;*.C;*.h" mimetype="text/x-c++-src;text/x-c++-hdr;text/x-c-hdr;text/x-c++-src">
  <highlighting>
    <list name="keywords">
      <item> class </item>
      <item> false </item>
      <item> friend </item>
      <item> inline </item>
      <item> namespace </item>
      <item> new </item>
      <item> delete </item>
	  <item> operator </item>
      <item> private </item>
      <item> protected </item>
      <item> public </item>
      <item> reinterpret_cast </item>
      <item> static_cast </item>
	  <item> dynamic_cast</item>
      <item> template </item>
      <item> this </item>
      <item> throw </item>
      <item> true </item>
      <item> try </item>
      <item> typeid </item>
      <item> typename </item>
      <item> using </item>
      <item> virtual </item>
      <item> and_eq </item>
      <item> and </item>
      <item> bitand </item>
      <item> bitor </item>
      <item> compl </item>
      <item> not_eq </item>
      <item> not </item>
      <item> or_eq </item>
      <item> or </item>
      <item> xor_eq </item>
      <item> xor </item>
      <item> bad_cast </item>
      <item> bad_typeid </item>
      <item> except </item>
      <item> finally </item>
      <item> type_info </item>
      <item> xalloc </item>
      <item> Q_EXPORT </item>
      <item> Q_OBJECT </item>
      <item> K_DCOP </item>
      <item> SLOT </item>
      <item> SIGNAL </item>
      <item> slots </item>
      <item> signals </item>
      <item> Q_PROPERTY </item>
      <item> Q_ENUMS </item>
      <item> Q_SETS </item>
      <item> Q_OVERRIDE </item>
      <item> Q_CLASSINFO </item>
      <item> TRUE </item>
      <item> FALSE </item>
      <item> break </item>
      <item> case </item>
      <item> continue </item>
      <item> default </item>
      <item> do </item>
      <item> else </item>
      <item> enum </item>
      <item> extern </item>
      <item> for </item>
      <item> goto </item>
      <item> if </item>
      <item> return </item>
      <item> sizeof </item>
      <item> struct </item>
      <item> switch </item>
      <item> typedef </item>
      <item> union </item>
      <item> while </item>
      <item> connect </item>
    </list>
    <list name="types">
      <item> bool </item>
      <item> wchar_t </item>
      <item> mutable </item>
      <item> uint </item>
      <item> auto </item>
      <item> char </item>
      <item> const </item>
      <item> double </item>
      <item> float </item>
      <item> int </item>
      <item> long </item>
      <item> register </item>
      <item> short </item>
      <item> signed </item>
      <item> static </item>
      <item> unsigned </item>
      <item> void </item>
      <item> volatile </item>
      <item> int16_t </item>
      <item> int32_t </item>
      <item> int8_t </item>
      <item> int64_t </item>
      <item> uint16_t </item>
      <item> uint32_t </item>
      <item> uint8_t </item>
      <item> uint64_t </item>
    </list>
    <contexts>
      <context attribute="0" lineEndContext="0" name="Normal">
        <keyword attribute="1" context="0" String="keywords" />
        <keyword attribute="2" context="0" String="types" />
        <Float attribute="6" context="0">
          <AnyChar String="fF" attribute="6" context="0"/>
        </Float>
        <HlCOct attribute="4" context="0"/>
        <HlCHex attribute="5" context="0"/>
        <Int attribute="3" context="0" >
          <StringDetect attribute="3" context="0" String="ULL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LUL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LLU" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="UL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LU" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="U" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="L" insensitive="TRUE"/>
        </Int>
        <HlCChar attribute="7" context="0"/>
        <DetectChar attribute="8" context="1" char="&quot;"/>
        <Detect2Chars attribute="10" context="2" char="/" char1="/"/>
        <Detect2Chars attribute="10" context="3" char="/" char1="*"/>
        <AnyChar attribute="11" context="0" String="!%&amp;()+,-&lt;=&gt;?[]^{|}~"/>
        <StringDetect attribute="10" context="8" String="#if 0" insensitive="FALSE"/>
        <RegExpr attribute="12" context="4" String="^#"/>
      </context>
      <context attribute="8" lineEndContext="0" name="String">
        <LineContinue attribute="8" context="6"/>
        <HlCStringChar attribute="9" context="1"/>
        <DetectChar attribute="8" context="0" char="&quot;"/>
      </context>
      <context attribute="10" lineEndContext="0" name="Commentar 1">
        <RegExpr attribute="3" context="2" String="(FIXME|TODO)" />
      </context>
      <context attribute="10" lineEndContext="3" name="Commentar 2">
        <RegExpr attribute="3" context="3" String="(FIXME|TODO)" />
        <Detect2Chars attribute="10" context="0" char="*" char1="/"/>
      </context>
      <context attribute="12" lineEndContext="0" name="Preprocessor">
        <LineContinue attribute="12" context="7"/>
        <RangeDetect attribute="13" context="4" char="&quot;" char1="&quot;"/>
        <RangeDetect attribute="13" context="4" char="&lt;" char1="&gt;"/>
        <Detect2Chars attribute="10" context="2" char="/" char1="/"/>
        <Detect2Chars attribute="10" context="5" char="/" char1="*"/>
      </context>
      <context attribute="10" lineEndContext="5" name="Commentar/Preprocessor">
        <Detect2Chars attribute="10" context="4" char="*" char1="/" />
      </context>
      <context attribute="0" lineEndContext="1" name="Some Context"/>
      <context attribute="0" lineEndContext="4" name="Some Context2"/>
      <context attribute="10" lineEndContext="8">
          <RegExpr attribute="3" context="8" String="(FIXME|TODO)" />
          <RegExpr attribute="10" context="0" String="^#endif" />
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword"  defStyleNum="dsKeyword"/>
      <itemData name="Data Type"  defStyleNum="dsDataType"/>
      <itemData name="Decimal"  defStyleNum="dsDecVal"/>
      <itemData name="Octal"  defStyleNum="dsBaseN"/>
      <itemData name="Hex"  defStyleNum="dsBaseN"/>
      <itemData name="Float"  defStyleNum="dsFloat"/>
      <itemData name="Char"  defStyleNum="dsChar"/>
      <itemData name="String"  defStyleNum="dsString"/>
      <itemData name="String Char"  defStyleNum="dsChar"/>
      <itemData name="Comment"  defStyleNum="dsComment"/>
      <itemData name="Symbol"  defStyleNum="dsNormal"/>
      <itemData name="Preprocessor"  defStyleNum="dsOthers"/>
      <itemData name="Prep. Lib"  defStyleNum="dsOthers"/> <!--,Qt::darkYellow,Qt::yellow,false,false)); -->
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="//" />
      <comment name="multiLine" start="/*" end="*/" />
    </comments>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/changelog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="ChangeLog" section="Other" extensions="ChangeLog" mimetype="">
        <highlighting>
          <contexts>
                <context attribute="0" lineEndContext="0">
                <RegExpr attribute="1" context="0" String="^\d\d\d\d\s*-\s*\d\d\s*-\s*\d\d.*$"/>
                </context>
          </contexts>
          <itemDatas>
                <itemData name="Normal Text" defStyleNum="dsNormal"/>
                <itemData name="Keyword" defStyleNum="dsKeyword"/>
                <itemData name="Identifier" defStyleNum="dsOthers"/>
                <itemData name="Types" defStyleNum="dsDataType"/>
                <itemData name="String" defStyleNum="dsString"/>
                <itemData name="Comment" defStyleNum="dsComment"/>
          </itemDatas>
        </highlighting>
  <general>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="XML/SGML" section="Markup" extensions="*.docbook;*.xml;*.rc;*.sgml" mimetype="text/sgml;text/xml;text/book">
  <highlighting>
    <contexts>
       <context attribute="0" lineEndContext="0">
         <RegExpr attribute="1" context="1" String="&lt;\s*\/?\s*[a-zA-Z_:][a-zA-Z0-9._:-]*" />
       </context>

       <context attribute="2" lineEndContext="1">
		 <Detect2Chars attribute="1" context="0" char="/" char1="&gt;" />
		 <DetectChar attribute="1" context="0" char="&gt;" />
         <RegExpr attribute="0" context="2" String="\s*=\s*" />
       </context>

       <context attribute="3" lineEndContext="2">
		 <RegExpr attribute="3" context="1" String="[A-Za-z0-9.-]*" />
         <DetectChar attribute="3" context="3" char="&quot;" />
       </context>

       <context attribute="3" lineEndContext="3">
         <DetectChar attribute="3" context="1" char="&quot;" />
       </context>

    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword" defStyleNum="dsKeyword"/>
      <itemData name="Identifier" defStyleNum="dsOthers"/>
      <itemData name="Types" defStyleNum="dsDataType"/>
      <itemData name="String" defStyleNum="dsString"/>
      <itemData name="Comment" defStyleNum="dsComment"/>
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="multiLine" start="&lt;!--" end="//--&gt;" />
    </comments>
    <keywords casesensitive="0" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name=".desktop" section="Other" extensions="*.desktop;*.kdelnk" mimetype="application/x-desktop">
  <highlighting>
    <contexts>
      <context attribute="2" lineEndContext="0" name="Normal">
        <RegExpr String="^\[.*\]$" attribute="Section" context="0"/>
        <RegExpr String="\[.*\]" attribute="Language" context="1"/>
        <DetectChar char="=" attribute="0" context="1"/>
      </context>
      <context attribute="0" lineEndContext="0" name="Value"/>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Section"  defStyleNum="dsKeyword"/>
      <itemData name="Key"  defStyleNum="dsDataType"/>
      <itemData name="Language"  defStyleNum="dsNormal" color="#0000FF" selColor="#ffffff" italic="0" bold="1"/>
    </itemDatas>
  </highlighting>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/java.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Java" section="Sources" extensions="*.java" mimetype="text/x-java-src">
  <highlighting>
    <list name="keywords">
      <item> abstract </item>
      <item> break </item>
      <item> case </item>
      <item> catch </item>
      <item> class </item>
      <item> continue </item>
      <item> default </item>
      <item> do </item>
      <item> else </item>
      <item> extends </item>
      <item> false </item>
      <item> finally </item>
      <item> for </item>
      <item> goto </item>
      <item> if </item>
      <item> implements </item>
      <item> import </item>
      <item> instanceof </item>
      <item> interface </item>
      <item> native </item>
      <item> new </item>
      <item> null </item>
      <item> package </item>
      <item> private </item>
      <item> protected </item>
      <item> public </item>
      <item> return </item>
      <item> super </item>
      <item> strictfp </item>
      <item> switch </item>
      <item> synchronized </item>
      <item> this </item>
      <item> throws </item>
      <item> throw </item>
      <item> transient </item>
      <item> true </item>
      <item> try </item>
      <item> volatile </item>
      <item> while </item>
    </list>
    <list name="types">
      <item> boolean </item>
      <item> byte </item>
      <item> char </item>
      <item> const </item>
      <item> double </item>
      <item> final </item>
      <item> float </item>
      <item> int </item>
      <item> long </item>
      <item> short </item>
      <item> static </item>
      <item> void </item>
    </list>
    <contexts>
      <context attribute="0" lineEndContext="0" name="Normal">
        <keyword attribute="1" context="0" String="keywords"/>
        <keyword attribute="2" context="0" String="types" />
        <Float attribute="6" context="0">
          <AnyChar String="fF" attribute="6" context="0"/>
        </Float>
        <HlCOct attribute="4" context="0"/>
        <HlCHex attribute="5" context="0"/>
        <Int attribute="3" context="0" >
          <StringDetect attribute="3" context="0" String="ULL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LUL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LLU" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="UL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LU" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="LL" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="U" insensitive="TRUE"/>
          <StringDetect attribute="3" context="0" String="L" insensitive="TRUE"/>
        </Int>
        <HlCChar attribute="7" context="0"/>
        <DetectChar attribute="8" context="1" char="&quot;"/>
        <Detect2Chars attribute="10" context="2" char="/" char1="/"/>
        <Detect2Chars attribute="10" context="3" char="/" char1="*"/>
        <AnyChar attribute="11" context="0" String="!%&amp;()+,-&lt;=&gt;?[]^{|}~"/>
      </context>
      <context attribute="8" lineEndContext="0" name="String">
        <LineContinue attribute="8" context="0"/>
        <HlCStringChar attribute="9" context="1"/>
        <DetectChar attribute="8" context="0" char="&quot;"/>
      </context>
      <context attribute="10" lineEndContext="0" name="Commentar 1"/>
      <context attribute="10" lineEndContext="3" name="Commentar 2">
        <Detect2Chars attribute="10" context="0" char="*" char1="/"/>
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword"  defStyleNum="dsKeyword"/>
      <itemData name="Data Type"  defStyleNum="dsDataType"/>
      <itemData name="Decimal"  defStyleNum="dsDecVal"/>
      <itemData name="Octal"  defStyleNum="dsBaseN"/>
      <itemData name="Hex"  defStyleNum="dsBaseN"/>
      <itemData name="Float"  defStyleNum="dsFloat"/>
      <itemData name="Char"  defStyleNum="dsChar"/>
      <itemData name="String"  defStyleNum="dsString"/>
      <itemData name="String Char"  defStyleNum="dsChar"/>
      <itemData name="Comment"  defStyleNum="dsComment"/>
      <itemData name="Symbol"  defStyleNum="dsNormal"/>
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="//" />
      <comment name="multiLine" start="/*" end="*/" />
    </comments>
    <keywords casesensitive="1" />
  </general>
</language>

=== furycd001/dots/fedorakde2/kdebase/kate/data/kbasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="KBasic" section="Sources" extensions="*.kbasic" mimetype="text/x-kbasic-src">
    <highlighting>
        <list name="keywords">
        <item> For </item>
        <item> Next</item>
        <item> Do </item>
        <item> Loop </item>
        <item> While </item>
        <item> Wend </item>
        <item> Until </item>
        <item> If </item>
        <item> Else </item>
        <item> End  </item>
        <item> Function </item>
        <item> Goto </item>
        <item> Sub  </item>
        <item> Implements </item>
        <item> In  </item>
        <item> Sub </item>
        <item> Private </item>
        <item> Public  </item>
        <item> Global </item>
        <item> As  </item>
        <item> Dim </item>
        <item> Set </item>
        <item> Let </item>
        <item> Get </item>
        <item> To </item>
        <item> Property </item>
        <item> True </item>
        <item> False </item>
        <item> Or  </item>
        <item> Not </item>
        <item> Xor  </item>
        <item> And  </item>
        <item> Then </item>
        <item> Exit </item>
        <item> Put </item>
        <item> Open </item>
        <item> Close </item>
        <item> Seek </item>
        <item> Print </item>
        <item> Input</item>
        <item> Output </item>
        <item> Repeat </item>
        <item> Load </item>
        <item> Unload </item>
        <item> Declare </item>
        <item> Option </item>
        <item> Explicit </item>
        </list>
        <list name="types">
        <item>Integer </item>
        <item>Long </item>
        <item>Byte </item>
        <item>Boolean </item>
        <item>Variant </item>
        <item>Single </item>
        <item>Double </item>
        <item>Currency </item>
        <item>String </item>
        <item>Object </item>
        <item>Control </item>
        </list>
        <contexts>
        <context attribute="0" lineEndContext="0">
        <keyword attribute="1" context="0" String="keywords"/>
        <keyword attribute="2" context="0" String="types"/>
        <Float attribute="4" context="0"/>
        <Int attribute="3" context="0"/>
        <DetectChar attribute="4" context="2" char="quot;"/>
        <DetectChar attribute="5" context="1" char="'"/>
        </context>
        <context attribute="5" lineEndContext="0"/>
        <context attribute="4" lineEndContext="0">
        <DetectChar attribute="4" context="0" char="'"/>
        </context>
        </contexts>
        <itemDatas>
        <itemData name="Normal Text" defStyleNum="dsNormal"/>
        <itemData name="Keyword" defStyleNum="dsKeyword"/>
        <itemData name="Identifier" defStyleNum="dsOthers"/>
        <itemData name="Types" defStyleNum="dsDataType"/>
        <itemData name="String" defStyleNum="dsString"/>
        <itemData name="Comment" defStyleNum="dsComment"/>
        </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="//" />
      <comment name="multiLine" start="/*" end="*/" />
    </comments>
    <keywords casesensitive="1" />
  </general>
</language>
